export default [
    {
        "id": 1,
        "name": "Cozy Urban Apartment",
        "location": "123 Main Street, Cityville, Country A",
        "propertyType": "Apartment",
        "price": 1200,
        "bedrooms": 2,
        "bathrooms": 1,
        "areaSqMeters": 80,
        "popularity": "high",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/1146993778/photo/modern-suburban-house-exterior.jpg?s=612x612&w=0&k=20&c=dPNhm16gFm9L8XCjYvxeeMq0CHuNdAjX-jtz5RUkjWY="
    },
    {
        "id": 2,
        "name": "Tranquil Countryside Retreat",
        "location": "456 Elm Avenue, Townsville, Country B",
        "propertyType": "House",
        "price": 1800,
        "bedrooms": 3,
        "bathrooms": 2,
        "areaSqMeters": 150,
        "popularity": "medium",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/1436217023/photo/exterior-of-a-blue-suburban-home.jpg?s=612x612&w=0&k=20&c=6n08rcEdza9Vehf5cHzk1uS0UKAN0qr3o884mbDvD5o="
    },
    {
        "id": 3,
        "name": "Modern Downtown Condo",
        "location": "789 Oak Road, Countryside, Country C",
        "propertyType": "Condo",
        "price": 1500,
        "bedrooms": 1,
        "bathrooms": 1,
        "areaSqMeters": 65,
        "popularity": "low",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/516810107/photo/two-story-house-exterior-with-front-yard-landscape.jpg?s=612x612&w=0&k=20&c=clQvNtTITc8Ejldq1PUT6eTtxojoDt1ZG-anL8OMmh4="
    },
    {
        "id": 4,
        "name": "Spacious Family Residence",
        "location": "101 Pine Lane, Suburbia, Country D",
        "propertyType": "House",
        "price": 2200,
        "bedrooms": 4,
        "bathrooms": 3,
        "areaSqMeters": 200,
        "popularity": "high",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/480960902/photo/large-modern-house-with-stone-and-walkway.jpg?s=612x612&w=0&k=20&c=eneh74Wn3zOjZ1-K3dz1bhlVYa_LpUmsGpiJTYrE-BE="
    },
    {
        "id": 5,
        "name": "Metroville Luxury Loft",
        "location": "202 Maple Street, Metroville, Country E",
        "propertyType": "Apartment",
        "price": 1350,
        "bedrooms": 2,
        "bathrooms": 2,
        "areaSqMeters": 90,
        "popularity": "medium",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/576909308/photo/nice-curb-appeal-of-two-level-house-mocha-exterior-paint.jpg?s=612x612&w=0&k=20&c=j5azrdfsozXsRAa6kJ5Spi_QdlefvaGD32JV2QpQuqI="
    },
    {
        "id": 6,
        "name": "Elegant Uptown Condo",
        "location": "303 Oak Avenue, Uptown, Country A",
        "propertyType": "Condo",
        "price": 1700,
        "bedrooms": 2,
        "bathrooms": 2,
        "areaSqMeters": 100,
        "popularity": "high",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/1276724606/photo/two-story-home-near-in-suburb-of-chicago.jpg?s=612x612&w=0&k=20&c=dziv8kRmV2ysgfYWz3CWczmU1BD51P9iCny-OQcuDSE="
    },
    {
        "id": 7,
        "name": "Country Retreat House",
        "location": "404 Elm Street, Countryside, Country B",
        "propertyType": "House",
        "price": 2000,
        "bedrooms": 3,
        "bathrooms": 2,
        "areaSqMeters": 160,
        "popularity": "low",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/1276724606/photo/two-story-home-near-in-suburb-of-chicago.jpg?s=612x612&w=0&k=20&c=dziv8kRmV2ysgfYWz3CWczmU1BD51P9iCny-OQcuDSE="
    },
    {
        "id": 8,
        "name": "Modern City Living Apartment",
        "location": "505 Pine Road, Suburbia, Country C",
        "propertyType": "Apartment",
        "price": 1250,
        "bedrooms": 1,
        "bathrooms": 1,
        "areaSqMeters": 70,
        "popularity": "medium",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/578085650/photo/beautiful-traditional-house-with-garage-and-driveway.jpg?s=612x612&w=0&k=20&c=hmST-duN2AefGyCYz5i6ozrcGTgEJCHmCaN80-aARpo="
    },
    {
        "id": 9,
        "name": "Spacious Family Home",
        "location": "606 Maple Avenue, Metroville, Country D",
        "propertyType": "House",
        "price": 2400,
        "bedrooms": 4,
        "bathrooms": 3,
        "areaSqMeters": 180,
        "popularity": "high",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/546195002/photo/house-exterior-view-of-entrance-porch-with-walkway-and-garage.jpg?s=612x612&w=0&k=20&c=CJiIxCFvav0PLihJrhv5J3gqkaWd2KmGImRg46xoa3g="
    },
    {
        "id": 10,
        "name": "Luxury Uptown Condo",
        "location": "707 Oak Lane, Uptown, Country A",
        "propertyType": "Condo",
        "price": 1600,
        "bedrooms": 2,
        "bathrooms": 2,
        "areaSqMeters": 110,
        "popularity": "medium",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/478360010/photo/large-house-with-driveway.jpg?s=612x612&w=0&k=20&c=pE-u4vOCZCdODr-N2mteyrCjWSQC09OqmOTIfpMMMWU="
    },
    {
        "id": 11,
        "name": "Classic Countryside House",
        "location": "808 Elm Road, Countryside, Country B",
        "propertyType": "House",
        "price": 2100,
        "bedrooms": 3,
        "bathrooms": 2,
        "areaSqMeters": 140,
        "popularity": "high",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/494838065/photo/grey-american-house-with-two-garage-doors.jpg?s=612x612&w=0&k=20&c=UMJ0BpBihgdKcclotDiclK1gAUHrDvQaCM6HvjeikkI="
    },
    {
        "id": 12,
        "name": "Charming Suburban Apartment",
        "location": "909 Pine Street, Suburbia, Country C",
        "propertyType": "Apartment",
        "price": 1300,
        "bedrooms": 1,
        "bathrooms": 1,
        "areaSqMeters": 75,
        "popularity": "low",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/155095657/photo/manufactured-home-park.jpg?s=612x612&w=0&k=20&c=xuYWuPHpc2Lq7HdnM2xqBcXMzqmZIEjrJGrJBUWx7Tc="
    },
    {
        "id": 13,
        "name": "Luxurious Modern Residence",
        "location": "1010 Maple Avenue, Metroville, Country D",
        "propertyType": "House",
        "price": 2600,
        "bedrooms": 4,
        "bathrooms": 3,
        "areaSqMeters": 200,
        "popularity": "medium",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/174920737/photo/new-cottage.jpg?s=612x612&w=0&k=20&c=Wrlb8SBvTT3bZrX70j9a7smsuEvZi1OyTBzQgKTH6oM="
    },
    {
        "id": 14,
        "name": "Uptown Charm Condo",
        "location": "1111 Oak Lane, Uptown, Country A",
        "propertyType": "Condo",
        "price": 1800,
        "bedrooms": 2,
        "bathrooms": 2,
        "areaSqMeters": 120,
        "popularity": "high",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/499332123/photo/big-two-story-house-view-of-entrance-porch-and-garage.jpg?s=612x612&w=0&k=20&c=kI1-dlcMZLHR9e2OHNE2FrVPm3VcyvgCSEUxJOUoOeY="
    },
    {
        "id": 15,
        "name": "Country Elegance House",
        "location": "1212 Elm Road, Countryside, Country B",
        "propertyType": "House",
        "price": 2300,
        "bedrooms": 3,
        "bathrooms": 2,
        "areaSqMeters": 180,
        "popularity": "low",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/520413053/photo/house-with-beautiful-curb-appeal-washington-real-estate.jpg?s=612x612&w=0&k=20&c=LQIT3gTC-3_zkBD55i952Cs_zNebT5FqmRR3VHbaiGo="
    },
    {
        "id": 16,
        "name": "Suburban Chic Apartment",
        "location": "1313 Pine Street, Suburbia, Country C",
        "propertyType": "Apartment",
        "price": 1400,
        "bedrooms": 1,
        "bathrooms": 1,
        "areaSqMeters": 80,
        "popularity": "medium",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/585780140/photo/luxurious-modern-house-with-entrance-high-ceiling-porch.jpg?s=612x612&w=0&k=20&c=ksdz_agLjlfXtSjEueB4p6deC8y3Cd3oeIZ3TvExX0c="
    },
    {
        "id": 17,
        "name": "Stunning Metroville Mansion",
        "location": "1414 Maple Avenue, Metroville, Country D",
        "propertyType": "House",
        "price": 2800,
        "bedrooms": 4,
        "bathrooms": 3,
        "areaSqMeters": 220,
        "popularity": "high",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/504653943/photo/house-exterior-in-light-blue-view-of-front-yard.jpg?s=612x612&w=0&k=20&c=PQ7H0G8pyttDxgMAhv-s1NgAPOU0UkRONkn164CJlzI="
    },
    {
        "id": 18,
        "name": "Uptown Elegance Condo",
        "location": "1515 Oak Lane, Uptown, Country A",
        "propertyType": "Condo",
        "price": 2000,
        "bedrooms": 2,
        "bathrooms": 2,
        "areaSqMeters": 130,
        "popularity": "medium",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/590166086/photo/luxury-two-level-house-exterior-with-garage-and-concrete-driveway.jpg?s=612x612&w=0&k=20&c=9Lwh89YiSYxjGUlUP-hyYIP2nNRZ9XNaIO_rno6KIYo="
    },
    {
        "id": 19,
        "name": "Countryside Serenity House",
        "location": "1616 Elm Road, Countryside, Country B",
        "propertyType": "House",
        "price": 2500,
        "bedrooms": 3,
        "bathrooms": 2,
        "areaSqMeters": 200,
        "popularity": "low",
        "status": "filled",
        "image": "https://media.istockphoto.com/id/544347356/photo/luxury-house-exterior-with-french-windows.jpg?s=612x612&w=0&k=20&c=BW414YoWPl4XM_Q_8Y2efvtiq0Du0J920Ht6N7hfGU4="
    },
    {
        "id": 20,
        "name": "Chic Suburban Apartment",
        "location": "1717 Pine Street, Suburbia, Country C",
        "propertyType": "Apartment",
        "price": 1450,
        "bedrooms": 1,
        "bathrooms": 1,
        "areaSqMeters": 85,
        "popularity": "medium",
        "status": "filled",
        "image": "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=600"
    }
]
